//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchung4U.API_SessionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonRequestData", Namespace="http://schemas.navitaire.com/WebServices/DataContracts/Session")]
    [System.SerializableAttribute()]
    public partial class LogonRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomainCode {
            get {
                return this.DomainCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainCodeField, value) != true)) {
                    this.DomainCodeField = value;
                    this.RaisePropertyChanged("DomainCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string RoleCode {
            get {
                return this.RoleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleCodeField, value) != true)) {
                    this.RoleCodeField = value;
                    this.RaisePropertyChanged("RoleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string TerminalInfo {
            get {
                return this.TerminalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalInfoField, value) != true)) {
                    this.TerminalInfoField = value;
                    this.RaisePropertyChanged("TerminalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenRequest", Namespace="http://schemas.navitaire.com/WebServices/DataContracts/Session")]
    [System.SerializableAttribute()]
    public partial class TokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Buchung4U.API_SessionService.ChannelType ChannelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Buchung4U.API_SessionService.SystemType SystemTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string TerminalInfo {
            get {
                return this.TerminalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalInfoField, value) != true)) {
                    this.TerminalInfoField = value;
                    this.RaisePropertyChanged("TerminalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Buchung4U.API_SessionService.ChannelType ChannelType {
            get {
                return this.ChannelTypeField;
            }
            set {
                if ((this.ChannelTypeField.Equals(value) != true)) {
                    this.ChannelTypeField = value;
                    this.RaisePropertyChanged("ChannelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Buchung4U.API_SessionService.SystemType SystemType {
            get {
                return this.SystemTypeField;
            }
            set {
                if ((this.SystemTypeField.Equals(value) != true)) {
                    this.SystemTypeField = value;
                    this.RaisePropertyChanged("SystemType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelType", Namespace="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")]
    public enum ChannelType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Web = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GDS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        API = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unmapped = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemType", Namespace="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")]
    public enum SystemType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WinRez = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FareManager = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduleManager = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WinManager = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsoleRez = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebRez = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebServicesAPI = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebServicesESC = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalService = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebReporting = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxAndFeeManager = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DCS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unmapped = -1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferSessionResponseData", Namespace="http://schemas.navitaire.com/WebServices/DataContracts/Session")]
    [System.SerializableAttribute()]
    public partial class TransferSessionResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APIWarningFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APIGeneralFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APICriticalFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APISecurityFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APIValidationFault))]
    public partial class APIFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTypeField, value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((this.UniqueIDField.Equals(value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIWarningFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault))]
    public partial class APIWarningFault : Buchung4U.API_SessionService.APIFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIUnhandledServerFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    public partial class APIUnhandledServerFault : Buchung4U.API_SessionService.APIWarningFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIGeneralFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    public partial class APIGeneralFault : Buchung4U.API_SessionService.APIFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APICriticalFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    public partial class APICriticalFault : Buchung4U.API_SessionService.APIFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APISecurityFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    public partial class APISecurityFault : Buchung4U.API_SessionService.APIFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIValidationFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
    [System.SerializableAttribute()]
    public partial class APIValidationFault : Buchung4U.API_SessionService.APIFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Buchung4U.API_SessionService.ValidationResult[] ValidationResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Buchung4U.API_SessionService.ValidationResult[] ValidationResults {
            get {
                return this.ValidationResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationResultsField, value) != true)) {
                    this.ValidationResultsField = value;
                    this.RaisePropertyChanged("ValidationResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResult", Namespace="http://www.navitaire.com/Ncl/Validation/ValidationResult")]
    [System.SerializableAttribute()]
    public partial class ValidationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Buchung4U.API_SessionService.SerializableDictionaryOfstringstring AnnotationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailedValidationDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Buchung4U.API_SessionService.SerializableDictionaryOfstringstring Annotations {
            get {
                return this.AnnotationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnotationsField, value) != true)) {
                    this.AnnotationsField = value;
                    this.RaisePropertyChanged("Annotations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailedValidationDescription {
            get {
                return this.FailedValidationDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedValidationDescriptionField, value) != true)) {
                    this.FailedValidationDescriptionField = value;
                    this.RaisePropertyChanged("FailedValidationDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="dictionary", Namespace="")]
    public partial class SerializableDictionaryOfstringstring : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SerializableDictionaryOfstringstring", "http://schemas.datacontract.org/2004/07/Navitaire.Ncl.Collections");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.navitaire.com/WebServices", ConfigurationName="API_SessionService.ISessionManager")]
    public interface ISessionManager {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ChangePassword weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePassword", ReplyAction="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIValidationFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIValidat" +
            "ionFaultFault", Name="APIValidationFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIUnhandl" +
            "edServerFaultFault", Name="APIUnhandledServerFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIFaultFa" +
            "ult", Name="APIFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIGeneralFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIGeneral" +
            "FaultFault", Name="APIGeneralFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APICriticalFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPICritica" +
            "lFaultFault", Name="APICriticalFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIWarningFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIWarning" +
            "FaultFault", Name="APIWarningFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APISecurityFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPISecurit" +
            "yFaultFault", Name="APISecurityFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        Buchung4U.API_SessionService.ChangePasswordResponse ChangePassword(Buchung4U.API_SessionService.ChangePasswordRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) von Nachricht "LogonRequest" nicht mit dem Standardwert (http://schemas.navitaire.com/WebServices) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/WebServices/ISessionManager/Logon", ReplyAction="http://schemas.navitaire.com/WebServices/ISessionManager/LogonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIFaultFault", Name="APIFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIValidationFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIValidationFaultF" +
            "ault", Name="APIValidationFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIUnhandledServerF" +
            "aultFault", Name="APIUnhandledServerFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIGeneralFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIGeneralFaultFaul" +
            "t", Name="APIGeneralFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APICriticalFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPICriticalFaultFau" +
            "lt", Name="APICriticalFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIWarningFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIWarningFaultFaul" +
            "t", Name="APIWarningFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APISecurityFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPISecurityFaultFau" +
            "lt", Name="APISecurityFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        Buchung4U.API_SessionService.LogonResponse Logon(Buchung4U.API_SessionService.LogonRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang Logout weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/WebServices/ISessionManager/Logout", ReplyAction="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIFaultFault", Name="APIFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIWarningFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIWarningFaultFau" +
            "lt", Name="APIWarningFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIValidationFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIValidationFault" +
            "Fault", Name="APIValidationFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APISecurityFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPISecurityFaultFa" +
            "ult", Name="APISecurityFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIUnhandledServer" +
            "FaultFault", Name="APIUnhandledServerFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIGeneralFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIGeneralFaultFau" +
            "lt", Name="APIGeneralFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APICriticalFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPICriticalFaultFa" +
            "ult", Name="APICriticalFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        Buchung4U.API_SessionService.LogoutResponse Logout(Buchung4U.API_SessionService.LogoutRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) von Nachricht "TransferSessionRequest" nicht mit dem Standardwert (http://schemas.navitaire.com/WebServices) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSession", ReplyAction="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APISecurityFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPISecuri" +
            "tyFaultFault", Name="APISecurityFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIUnhandledServerFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIUnhand" +
            "ledServerFaultFault", Name="APIUnhandledServerFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIFaultF" +
            "ault", Name="APIFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIGeneralFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIGenera" +
            "lFaultFault", Name="APIGeneralFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIValidationFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIValida" +
            "tionFaultFault", Name="APIValidationFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APICriticalFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPICritic" +
            "alFaultFault", Name="APICriticalFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(Buchung4U.API_SessionService.APIWarningFault), Action="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIWarnin" +
            "gFaultFault", Name="APIWarningFault", Namespace="http://schemas.navitaire.com/WebServices/FaultContracts")]
        Buchung4U.API_SessionService.TransferSessionResponse TransferSession(Buchung4U.API_SessionService.TransferSessionRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang KeepAlive weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.navitaire.com/WebServices/ISessionManager/KeepAlive", ReplyAction="http://schemas.navitaire.com/WebServices/ISessionManager/KeepAliveResponse")]
        Buchung4U.API_SessionService.KeepAliveResponse KeepAlive(Buchung4U.API_SessionService.KeepAliveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordRequest", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public int ContractVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order=0)]
        public Buchung4U.API_SessionService.LogonRequestData logonRequestData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order=1)]
        public string newPassword;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(int ContractVersion, Buchung4U.API_SessionService.LogonRequestData logonRequestData, string newPassword) {
            this.ContractVersion = ContractVersion;
            this.logonRequestData = logonRequestData;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        public ChangePasswordResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogonRequest", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class LogonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public int ContractVersion;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public bool EnableExceptionStackTrace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order=0)]
        public Buchung4U.API_SessionService.LogonRequestData logonRequestData;
        
        public LogonRequest() {
        }
        
        public LogonRequest(int ContractVersion, bool EnableExceptionStackTrace, Buchung4U.API_SessionService.LogonRequestData logonRequestData) {
            this.ContractVersion = ContractVersion;
            this.EnableExceptionStackTrace = EnableExceptionStackTrace;
            this.logonRequestData = logonRequestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogonResponse", WrapperNamespace="http://schemas.navitaire.com/WebServices", IsWrapped=true)]
    public partial class LogonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices", Order=0)]
        public string Signature;
        
        public LogonResponse() {
        }
        
        public LogonResponse(string Signature) {
            this.Signature = Signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutRequest", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public int ContractVersion;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public bool EnableExceptionStackTrace;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public string MessageContractVersion;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public string Signature;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(int ContractVersion, bool EnableExceptionStackTrace, string MessageContractVersion, string Signature) {
            this.ContractVersion = ContractVersion;
            this.EnableExceptionStackTrace = EnableExceptionStackTrace;
            this.MessageContractVersion = MessageContractVersion;
            this.Signature = Signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        public LogoutResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferSessionRequest", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class TransferSessionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public int ContractVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order=0)]
        public Buchung4U.API_SessionService.TokenRequest tokenRequest;
        
        public TransferSessionRequest() {
        }
        
        public TransferSessionRequest(int ContractVersion, Buchung4U.API_SessionService.TokenRequest tokenRequest) {
            this.ContractVersion = ContractVersion;
            this.tokenRequest = tokenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferSessionResponse", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class TransferSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order=0)]
        public Buchung4U.API_SessionService.TransferSessionResponseData TransferSessionResponseData;
        
        public TransferSessionResponse() {
        }
        
        public TransferSessionResponse(Buchung4U.API_SessionService.TransferSessionResponseData TransferSessionResponseData) {
            this.TransferSessionResponseData = TransferSessionResponseData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepAliveRequest", WrapperNamespace="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped=true)]
    public partial class KeepAliveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public int ContractVersion;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public bool EnableExceptionStackTrace;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public string MessageContractVersion;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.navitaire.com/WebServices")]
        public string Signature;
        
        public KeepAliveRequest() {
        }
        
        public KeepAliveRequest(int ContractVersion, bool EnableExceptionStackTrace, string MessageContractVersion, string Signature) {
            this.ContractVersion = ContractVersion;
            this.EnableExceptionStackTrace = EnableExceptionStackTrace;
            this.MessageContractVersion = MessageContractVersion;
            this.Signature = Signature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepAliveResponse {
        
        public KeepAliveResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionManagerChannel : Buchung4U.API_SessionService.ISessionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionManagerClient : System.ServiceModel.ClientBase<Buchung4U.API_SessionService.ISessionManager>, Buchung4U.API_SessionService.ISessionManager {
        
        public SessionManagerClient() {
        }
        
        public SessionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Buchung4U.API_SessionService.ChangePasswordResponse Buchung4U.API_SessionService.ISessionManager.ChangePassword(Buchung4U.API_SessionService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public void ChangePassword(int ContractVersion, Buchung4U.API_SessionService.LogonRequestData logonRequestData, string newPassword) {
            Buchung4U.API_SessionService.ChangePasswordRequest inValue = new Buchung4U.API_SessionService.ChangePasswordRequest();
            inValue.ContractVersion = ContractVersion;
            inValue.logonRequestData = logonRequestData;
            inValue.newPassword = newPassword;
            Buchung4U.API_SessionService.ChangePasswordResponse retVal = ((Buchung4U.API_SessionService.ISessionManager)(this)).ChangePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Buchung4U.API_SessionService.LogonResponse Buchung4U.API_SessionService.ISessionManager.Logon(Buchung4U.API_SessionService.LogonRequest request) {
            return base.Channel.Logon(request);
        }
        
        public string Logon(int ContractVersion, bool EnableExceptionStackTrace, Buchung4U.API_SessionService.LogonRequestData logonRequestData) {
            Buchung4U.API_SessionService.LogonRequest inValue = new Buchung4U.API_SessionService.LogonRequest();
            inValue.ContractVersion = ContractVersion;
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace;
            inValue.logonRequestData = logonRequestData;
            Buchung4U.API_SessionService.LogonResponse retVal = ((Buchung4U.API_SessionService.ISessionManager)(this)).Logon(inValue);
            return retVal.Signature;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Buchung4U.API_SessionService.LogoutResponse Buchung4U.API_SessionService.ISessionManager.Logout(Buchung4U.API_SessionService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(int ContractVersion, bool EnableExceptionStackTrace, string MessageContractVersion, string Signature) {
            Buchung4U.API_SessionService.LogoutRequest inValue = new Buchung4U.API_SessionService.LogoutRequest();
            inValue.ContractVersion = ContractVersion;
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace;
            inValue.MessageContractVersion = MessageContractVersion;
            inValue.Signature = Signature;
            Buchung4U.API_SessionService.LogoutResponse retVal = ((Buchung4U.API_SessionService.ISessionManager)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Buchung4U.API_SessionService.TransferSessionResponse Buchung4U.API_SessionService.ISessionManager.TransferSession(Buchung4U.API_SessionService.TransferSessionRequest request) {
            return base.Channel.TransferSession(request);
        }
        
        public Buchung4U.API_SessionService.TransferSessionResponseData TransferSession(int ContractVersion, Buchung4U.API_SessionService.TokenRequest tokenRequest) {
            Buchung4U.API_SessionService.TransferSessionRequest inValue = new Buchung4U.API_SessionService.TransferSessionRequest();
            inValue.ContractVersion = ContractVersion;
            inValue.tokenRequest = tokenRequest;
            Buchung4U.API_SessionService.TransferSessionResponse retVal = ((Buchung4U.API_SessionService.ISessionManager)(this)).TransferSession(inValue);
            return retVal.TransferSessionResponseData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Buchung4U.API_SessionService.KeepAliveResponse Buchung4U.API_SessionService.ISessionManager.KeepAlive(Buchung4U.API_SessionService.KeepAliveRequest request) {
            return base.Channel.KeepAlive(request);
        }
        
        public void KeepAlive(int ContractVersion, bool EnableExceptionStackTrace, string MessageContractVersion, string Signature) {
            Buchung4U.API_SessionService.KeepAliveRequest inValue = new Buchung4U.API_SessionService.KeepAliveRequest();
            inValue.ContractVersion = ContractVersion;
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace;
            inValue.MessageContractVersion = MessageContractVersion;
            inValue.Signature = Signature;
            Buchung4U.API_SessionService.KeepAliveResponse retVal = ((Buchung4U.API_SessionService.ISessionManager)(this)).KeepAlive(inValue);
        }
    }
}
